services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=utf-8   # 파이썬 입출력 인코딩 설정
      - LANG=C.UTF-8             # 시스템 기본 언어 설정
